### ISSUE TITLE
Mismatch ap bssid in dual band

### ISSUE THREAD

**Issue by mywalkb** [Sinf0r0s0/pmkid-auto#1]
Thank you for your work, it's help me for my idea.
I tested the script on many devices, on my android smartphone I discovered an issue.
There are some wifi networks in dual band 2.4/5 Ghz with the same ESSID but different BSSID, with the scan a BSSID is discovered, but when we try to get pmkid not always is used the same BSSID so the PMKID is generated for a different BSSID and the result is: password not found.
In my bash script I solved the issue setting the parameter bssid in wpa.conf, so it match ESSID and BSSID.
It should be easy also in function over_conf pmkidauto/auto.py

**Comment by Ilg-modder** [comment]
Bro r u there it's giving me error basis is far away or is not vulnerable 😭I try this in 11 network

**Comment by Ilg-modder** [comment]
What's the problem can u tell me

**Comment by mywalkb** [comment]
> Bro r u there it's giving me error basis is far away or is not vulnerable 😭I try this in 11 network

not all APs are vulnerable, it is normal that out of 11 you don't find even one. The producers are correcting it.
For example in one case out of 20 APs only one is vulnerable.

**Comment by Ilg-modder** [comment]
I get it bro after 2 days research ❤️thanks
